# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8397ce39e7d1c55700309b953f56cd40a509d88399b7e6719b160737db417a8e94d3205fcf5b2c2861b77ce88b12f60c3ddf3650412908cc8a8fa23648557fea

test:
  secret_key_base: 501f1546dc91298a1031f6706b33cb8e82b481006ae62155822eb946138d7e3f185c8beae4c937d57bcef86c26caa6c7dd5efcd5bb1026459f0afb5aa69b78d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
